courts_index:
    path:     /
    defaults: { _controller: "AppBundle:Court:index" }
    methods:  GET

courts_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Court:show" }
    methods:  GET

courts_new:
    path:     /new
    defaults: { _controller: "AppBundle:Court:new" }
    methods:  [GET, POST]

courts_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Court:edit" }
    methods:  [GET, POST]

courts_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Court:delete" }
    methods:  DELETE
