reservations_index:
    path:     /
    defaults: { _controller: "AppBundle:Reservation:index" }
    methods:  GET

reservations_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Reservation:show" }
    methods:  GET

reservations_new:
    path:     /new
    defaults: { _controller: "AppBundle:Reservation:new" }
    methods:  [GET, POST]

reservations_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Reservation:edit" }
    methods:  [GET, POST]

reservations_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Reservation:delete" }
    methods:  DELETE
