padel_api_courts:
    type: rest
    resource: "@AppBundle/Controller/CourtFOSController.php"
    name_prefix:  api2_courts_
    
padel_api_users:
    type: rest
    resource: "@AppBundle/Controller/UserFOSController.php"
    name_prefix:  api2_users_
    
padel_api_groups:
    type: rest
    resource: "@AppBundle/Controller/GroupFOSController.php"
    name_prefix:  api2_groups_
    
padel_api_reservations:
    type: rest
    resource: "@AppBundle/Controller/ReservationFOSController.php"
    name_prefix:  api2_reservations_
